name: publish

on:
  push:
    branches: [ "staging" ]

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: false
      
      - name: Bundle install
        run: bundle install
      
      - name: Parse feed.xml
        run: ruby generate_feed_includes.rb

      - name: Jekyll Build
        run: bundle exec jekyll build
