name: publish

on:
  push:
    branches: [ "main" ]

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      
      - name: Parse feed.xml
        run: ruby generate_feed_includes.rb

      - name: Jekyll Build
        run: |
          bundle install
          bundle exec jekyll build
      
      - uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          neocities_supporter: false # set this to true if you have a supporter account and want to bypass unsuported files filter
          preview_before_deploy: true # print a deployment plan prior to waiting for files to upload
          dist_dir: _site
