name: publish

on:
  push:
    branches: [ "main" ]

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Bundle Install
        run: |
          gem install --user-install bundle
          bundle install

      - name: Build
        run: jekyll exec build
