name: publish

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # Trigger every day

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set timezone to Toronto
        run: sudo timedatectl set-timezone "America/Toronto"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
          cache-version: 1 # https://github.com/ruby/setup-ruby#caching-bundle-install-automatically
      
      - name: Bundle install
        run: bundle install

      - name: Convert member files to valid YAML files
        run: bash scripts/members_to_yaml.sh

      - name: Validate Members against schema
        uses: cardinalby/schema-validator-action@v3
        with:
          file: .member_yaml/*
          schema: scripts/member_schema.json
      
      - name: Parse feed.xml
        run: ruby scripts/generate_feed_includes.rb

      - name: Jekyll Build
        run: bundle exec jekyll build
      
      - uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          neocities_supporter: false # set this to true if you have a supporter account and want to bypass unsuported files filter
          preview_before_deploy: true # print a deployment plan prior to waiting for files to upload
          dist_dir: _site
